version: '3.9'

services:
  mongo:
    image: mongo:4.2.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-P@ssw0rD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-urlShortener}
    networks:
      - short-ly_mongo_network

  short-ly:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    image: short-ly_image
    container_name: short-ly_ctr
    environment:
      # If you have a connection issue to MongoDB in docker-compose, refer here : https://stackoverflow.com/questions/43162897/how-to-connect-to-mongodb-using-docker-compose/43163074
      MONGODB_CONNECTION_URL: ${MONGODB_CONNECTION_URL}
      PORT: ${PORT:-5000}
    ports:
      - 5000:5000
    networks:
      - short-ly_mongo_network